### ISSUE TITLE
I don't think this will work on Heroku

### ISSUE THREAD

**Issue by ericgross** [contentful/contentful-webhook-listener.rb#3]
In that situation, there is only one port exposed - wouldn't this be better as an engine to run in our existing apps?

**Comment by dlitvakb** [comment]
Hey @ericgross,

If you have a pre-existing WEBrick app, you can just include it as a Controller in your app, and use it.

You can even wrap it in a Rack compatible envelope and launch it in any other Rack compatible environment.

Though the main use-case we developed this for was to use as stand-alone apps (or with multiple webhook listener functions inside the same app). Using the 2 methods I described above, you can include it in your existing apps.

Hope this helps
