### ISSUE TITLE
App will throw error when using the request 

### ISSUE THREAD

**Issue by edugonch** [contentful/contentful-webhook-listener.rb#4]
The app throw an I/O error when the request is used in the controller, I trace the error and found that in the controller/base.rb when it created the thread it is the source of the problem.

Maybe the variable is not lock or there is a problem with the scope.

If you flush the request variable before creating the thread like "puts request" will solve the problem and the request variable will work in the controller.

**Comment by dlitvakb** [comment]
Hey @edugonch,

Thanks for the submission!

I'll look into it soon
